# Generated by Django 4.2.11 on 2024-04-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='aircraft_type',
            new_name='aircraft_type_name',
        ),
    ]
