# Generated by Django 4.2.11 on 2024-04-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_rename_aircraft_type_aircraft_aircraft_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='current_status',
            field=models.ForeignKey(help_text='Current Status type of aircraft.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_status_type', to='bookingapp.aircraftstatustype'),
        ),
    ]
