# Generated by Django 4.2.11 on 2024-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_remove_flightregistration_airline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Select End Date', null=True),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='from_date',
            field=models.DateField(blank=True, help_text='Select From Date', null=True),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='schedule_type',
            field=models.CharField(choices=[('specific_date', 'specific_date'), ('date_range', 'date_range')], help_text='Select the Schedule type for scheduling the flight', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Select Specific Date', null=True),
        ),
    ]
