# Generated by Django 4.2.11 on 2024-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_flightschedule_end_date_flightschedule_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightfrequencies',
            name='days_of_operation',
        ),
        migrations.AddField(
            model_name='flightfrequencies',
            name='days_of_operation',
            field=models.ManyToManyField(related_name='day_of_operations', to='bookingapp.dayofoperation'),
        ),
    ]
